@startuml

abstract class Creature
abstract class Animal extends Creature
abstract class Fish extends Creature

interface Flyable
interface Swimmable
interface Talkable

class Parrot extends Animal implements Flyable, Talkable
class Tiger extends Animal
class People extends Animal implements Talkable


class Whale extends Fish implements Swimmable

@enduml